compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.7.0.cjs

packageExtensions:
  react-native-web@*:
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@react-navigation/native-stack@*":
    peerDependencies:
      react: "*"
      react-native: "*"
  moti@*:
    peerDependencies:
      react-native-reanimated: "*"
